/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BirdsRouteImport } from './routes/birds'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpeciesControlRouteImport } from './routes/species-control'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiLiveStreamRouteImport } from './routes/api/live-stream'
import { Route as BirdsIndexRouteImport } from './routes/birds.index'
import { Route as BirdsComNameRouteImport } from './routes/birds.$comName'
import { Route as DayDateRouteImport } from './routes/day.$date'
import { Route as SpeciesIndexRouteImport } from './routes/species.index'
import { Route as SpeciesComNameRouteImport } from './routes/species.$comName'
import { Route as ApiAudioDateSpeciesAndFileRouteImport } from './routes/api/audio/$date/$speciesAndFile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BirdsRoute = BirdsRouteImport.update({
  id: '/birds',
  path: '/birds',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesControlRoute = SpeciesControlRouteImport.update({
  id: '/species-control',
  path: '/species-control',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveStreamRoute = ApiLiveStreamRouteImport.update({
  id: '/api/live-stream',
  path: '/api/live-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const BirdsIndexRoute = BirdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BirdsRoute,
} as any)
const BirdsComNameRoute = BirdsComNameRouteImport.update({
  id: '/$comName',
  path: '/$comName',
  getParentRoute: () => BirdsRoute,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesIndexRoute = SpeciesIndexRouteImport.update({
  id: '/species/',
  path: '/species/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesComNameRoute = SpeciesComNameRouteImport.update({
  id: '/species/$comName',
  path: '/species/$comName',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioDateSpeciesAndFileRoute =
  ApiAudioDateSpeciesAndFileRouteImport.update({
    id: '/api/audio/$date/$speciesAndFile',
    path: '/api/audio/$date/$speciesAndFile',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/birds': typeof BirdsRouteWithChildren
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/species-control': typeof SpeciesControlRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/birds/$comName': typeof BirdsComNameRoute
  '/day/$date': typeof DayDateRoute
  '/species/$comName': typeof SpeciesComNameRoute
  '/birds/': typeof BirdsIndexRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/species-control': typeof SpeciesControlRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/birds/$comName': typeof BirdsComNameRoute
  '/day/$date': typeof DayDateRoute
  '/species/$comName': typeof SpeciesComNameRoute
  '/birds': typeof BirdsIndexRoute
  '/species': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/birds': typeof BirdsRouteWithChildren
  '/detections': typeof DetectionsRoute
  '/learn': typeof LearnRoute
  '/live': typeof LiveRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/species-control': typeof SpeciesControlRoute
  '/stats': typeof StatsRoute
  '/timeline': typeof TimelineRoute
  '/today': typeof TodayRoute
  '/api/live-stream': typeof ApiLiveStreamRoute
  '/birds/$comName': typeof BirdsComNameRoute
  '/day/$date': typeof DayDateRoute
  '/species/$comName': typeof SpeciesComNameRoute
  '/birds/': typeof BirdsIndexRoute
  '/species/': typeof SpeciesIndexRoute
  '/api/audio/$date/$speciesAndFile': typeof ApiAudioDateSpeciesAndFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/birds'
    | '/detections'
    | '/learn'
    | '/live'
    | '/review'
    | '/settings'
    | '/species-control'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/api/live-stream'
    | '/birds/$comName'
    | '/day/$date'
    | '/species/$comName'
    | '/birds/'
    | '/species/'
    | '/api/audio/$date/$speciesAndFile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/detections'
    | '/learn'
    | '/live'
    | '/review'
    | '/settings'
    | '/species-control'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/api/live-stream'
    | '/birds/$comName'
    | '/day/$date'
    | '/species/$comName'
    | '/birds'
    | '/species'
    | '/api/audio/$date/$speciesAndFile'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/birds'
    | '/detections'
    | '/learn'
    | '/live'
    | '/review'
    | '/settings'
    | '/species-control'
    | '/stats'
    | '/timeline'
    | '/today'
    | '/api/live-stream'
    | '/birds/$comName'
    | '/day/$date'
    | '/species/$comName'
    | '/birds/'
    | '/species/'
    | '/api/audio/$date/$speciesAndFile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BirdsRoute: typeof BirdsRouteWithChildren
  DetectionsRoute: typeof DetectionsRoute
  LearnRoute: typeof LearnRoute
  LiveRoute: typeof LiveRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SpeciesControlRoute: typeof SpeciesControlRoute
  StatsRoute: typeof StatsRoute
  TimelineRoute: typeof TimelineRoute
  TodayRoute: typeof TodayRoute
  ApiLiveStreamRoute: typeof ApiLiveStreamRoute
  DayDateRoute: typeof DayDateRoute
  SpeciesComNameRoute: typeof SpeciesComNameRoute
  SpeciesIndexRoute: typeof SpeciesIndexRoute
  ApiAudioDateSpeciesAndFileRoute: typeof ApiAudioDateSpeciesAndFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birds': {
      id: '/birds'
      path: '/birds'
      fullPath: '/birds'
      preLoaderRoute: typeof BirdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species-control': {
      id: '/species-control'
      path: '/species-control'
      fullPath: '/species-control'
      preLoaderRoute: typeof SpeciesControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live-stream': {
      id: '/api/live-stream'
      path: '/api/live-stream'
      fullPath: '/api/live-stream'
      preLoaderRoute: typeof ApiLiveStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birds/': {
      id: '/birds/'
      path: '/'
      fullPath: '/birds/'
      preLoaderRoute: typeof BirdsIndexRouteImport
      parentRoute: typeof BirdsRoute
    }
    '/birds/$comName': {
      id: '/birds/$comName'
      path: '/$comName'
      fullPath: '/birds/$comName'
      preLoaderRoute: typeof BirdsComNameRouteImport
      parentRoute: typeof BirdsRoute
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/': {
      id: '/species/'
      path: '/species'
      fullPath: '/species/'
      preLoaderRoute: typeof SpeciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species/$comName': {
      id: '/species/$comName'
      path: '/species/$comName'
      fullPath: '/species/$comName'
      preLoaderRoute: typeof SpeciesComNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/$date/$speciesAndFile': {
      id: '/api/audio/$date/$speciesAndFile'
      path: '/api/audio/$date/$speciesAndFile'
      fullPath: '/api/audio/$date/$speciesAndFile'
      preLoaderRoute: typeof ApiAudioDateSpeciesAndFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BirdsRouteChildren {
  BirdsComNameRoute: typeof BirdsComNameRoute
  BirdsIndexRoute: typeof BirdsIndexRoute
}

const BirdsRouteChildren: BirdsRouteChildren = {
  BirdsComNameRoute: BirdsComNameRoute,
  BirdsIndexRoute: BirdsIndexRoute,
}

const BirdsRouteWithChildren = BirdsRoute._addFileChildren(BirdsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BirdsRoute: BirdsRouteWithChildren,
  DetectionsRoute: DetectionsRoute,
  LearnRoute: LearnRoute,
  LiveRoute: LiveRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SpeciesControlRoute: SpeciesControlRoute,
  StatsRoute: StatsRoute,
  TimelineRoute: TimelineRoute,
  TodayRoute: TodayRoute,
  ApiLiveStreamRoute: ApiLiveStreamRoute,
  DayDateRoute: DayDateRoute,
  SpeciesComNameRoute: SpeciesComNameRoute,
  SpeciesIndexRoute: SpeciesIndexRoute,
  ApiAudioDateSpeciesAndFileRoute: ApiAudioDateSpeciesAndFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
